import type { Goal } from "./simulate.ts";

export const script: readonly Goal[] = [
  { order: 10, own: "woodenAxe", count: 1 },
  { order: 20, own: "woodenAxe", count: 2 },
  { order: 30, own: "woodenAxe", count: 3 },
  { order: 40, own: "woodenPickaxe", count: 1 },
  { order: 50, own: "quarry", count: 1 },
  { order: 60, own: "woodenAxe", count: 5 },
  { order: 70, own: "quarry", count: 3 },
  { order: 80, own: "woodenPickaxe", count: 2 },
  { order: 100, own: "coalMine", count: 2 },
  { order: 110, own: "quarry", count: 5 },
  { order: 120, own: "furnace", count: 1 },
  { order: 130, own: "woodenAxe", count: 8 },
  { order: 140, own: "coalMine", count: 4 },
  { order: 90, own: "stonePickaxe", count: 1 },
  { order: 150, own: "caves", count: 1 },
  { order: 160, own: "woodenAxe", count: 12 },
  { order: 170, own: "furnace", count: 2 },
  { order: 200, own: "woodenAxe", count: 15 },
  { order: 210, own: "furnace", count: 3 },
  { order: 240, own: "ironPickaxe", count: 1 },
  { order: 180, own: "smelter", count: 1 },
  { order: 190, own: "ironMine", count: 2 },
  { order: 220, own: "smelter", count: 2 },
  { order: 230, own: "ironMine", count: 3 },
  { order: 250, own: "woodenAxe", count: 20 },
  { order: 260, own: "torchWorkshop", count: 1 },
  { order: 270, own: "quarry", count: 8 },
  { order: 280, own: "coalMine", count: 6 },
  { order: 290, own: "ironMine", count: 5 },
  { order: 300, own: "furnace", count: 5 },
  { order: 310, own: "smelter", count: 4 },
  { order: 320, own: "woodenAxe", count: 25 },
  { order: 330, own: "torchWorkshop", count: 2 },
  { order: 340, own: "deepCaves", count: 1 },
  { order: 390, own: "diamondPickaxe", count: 1 },
  { order: 480, own: "nether", count: 1 },
  { order: 520, own: "netheritePickaxe", count: 1 },
];
